Sopt-Bridge/Bridge-Web

src/App.vue
src/components/NavigationBar.vue

feat : add NavigationBar.vue

---

src/components/Drawer/Navdrawer.vue
src/components/Poster/MainPoster.vue
src/components/index.js
src/main.js
src/pages/Home.vue

feat : add Main Poster Component Vue

---

src/components/Contents/Recommended.vue
src/components/Contents/Trending.vue
src/components/Contents/VideoCard.vue
src/components/Drawer/Navdrawer.vue
src/components/index.js
src/pages/Home.vue

add Trending and Recommended Components of Vue

feat : add Trending and Recommended Components of Vue

---

src/components/index.js

add ViMain and ViSidebar Component

fix : add ViMain and ViSidebar Component

---

src/pages/Request/Request-Main.vue
src/pages/VideoContents.vue
src/router/home.js
src/router/index.js
src/router/login.js
src/router/video.js

The router has been subdivided

refactor : The router has been subdivided

---

src/components/Toolbar/Toolbar.vue

add router to home when click image of home

feat : add router to home when click image of home

---

src/components/Toolbar/Toolbar.vue

add v-menu function of Vuetify at perm_identity icon

feat : add v-menu function of Vuetify at perm_identity icon

---

src/components/Pagination/RequestPagination.vue
src/components/Toolbar/Toolbar.vue
src/pages/Request/Request.vue
src/pages/Request/RequestMain.vue
src/pages/Request/RequestWrite.vue
src/router/request.js

add RequestWrite page of project

feat : add RequestWrite page of project

---

src/pages/Request/RequestDetail.vue
src/router/request.js

add RequestDetail Page of project. I have to add something to it!

feat : add RequestDetail Page of project

---

src/components/Comment/Reply.vue
src/components/Comment/RequestComment.vue
src/pages/Request/RequestDetail.vue

finish making RequestComment component without responsive web

feat : finish making RequestComment component without responsive web

---

src/components/Drawer/Navdrawer.vue

fix : change size of more icon

---

src/App.vue
src/components/Contents/Contents.vue
src/components/Drawer/Navdrawer.vue
src/components/Toolbar/SearchBar.vue
src/components/Toolbar/Toolbar.vue
src/pages/Home.vue
src/style/layout.scss

toolbar, navigationdrawer, contents changed.

refactor : toolbar, navigationdrawer, contents

---

src/components/Drawer/Navdrawer.vue
src/components/Toolbar/SearchBar.vue
src/components/Toolbar/Toolbar.vue

change layout of toolbar when under size of 510px

refactor : change layout of toolbar when under size of 510px

---

src/App.vue
src/components/Poster/MainPoster.vue

feat : add swiper at main-poster

---

src/components/Toolbar/SearchBar.vue

style : 최근 검색어가 없을 때의 레이아웃 수정

---

src/components/Card/VideoCard.vue
src/components/Vi-Main/Vi-Main.vue
src/components/Vi-Main/ViM-Infor.vue
src/components/Vi-Main/ViM-Video.vue
src/components/Vi-Sidebar/Vi-Sidebar.vue
src/components/Vi-Sidebar/ViS-Comments.vue
src/components/Vi-Sidebar/ViS-Recommended.vue
src/components/Vi-Sidebar/ViS-Tabs.vue
src/components/Vi-Sidebar/ViS-infro.vue
src/pages/VideoContents.vue

refactor : videoContent page 레이아웃 반응형으로

---

src/components/Poster/MainPoster.vue

add autoplay swiper option at main poster

feat : add autoplay swiper option at main poster

---

src/components/Toolbar/Toolbar.vue

change layout of myinfo icon of toolbar

refactor : change layout of myinfo icon of toolbar

---

src/App.vue
src/components/Toolbar/Toolbar.vue

fix : myinfo css 고침

---

src/components/Library.vue
src/components/Modal/Modal.vue
src/components/Modal/MyPage-modal.vue
src/components/Modal/Subscribe-modal.vue
src/pages/Subscribe/Subscribe.vue

subscribe page에 modal 사용되는 컴포넌트 만듬
modal 컴포넌트를 이용해서 subscrbie-modal 컴포넌트 만드는 중

feat : subscribe page에 modal 사용되는 컴포넌트 만듬

---

src/components/Comment/Comment.vue
src/components/Comment/CommentAllInOne.vue
src/components/Comment/Reply.vue
src/components/Comment/RequestComment.vue
src/components/Vi-Sidebar/ViS-Comments.vue

Comment, Reply, Reply작성 폼 한 컴포넌트로 묶고 reply기능을 활성화

refactor : Comment, Reply, Reply작성 폼 한 컴포넌트로 묶고 reply기능을 활성화

---

src/components/Drawer/Navdrawer.1.vue
src/pages/Home.vue
src/pages/MyPage.vue

Navdrawer.vue 공통으로 사용하게 변경
Home page와 MyPage page에서 공통으로 Navdrawer. 사용

fix : Navdrawer.vue 공통으로 사용하게 변경

---

src/components/Toolbar/SearchBar.vue
src/pages/Request/RequestMain.vue
src/pages/Search.vue

fix : 해시태그 검색 안되는 문제 수정

---

src/components/Toolbar/SearchBar.vue
src/components/Toolbar/Toolbar.vue

search버튼을 통하여 검색 또한 할 수 있도록 기능 추가

feat : search버튼을 통하여 검색 또한 할 수 있도록 기능 추가

---

src/components/Toolbar/SearchBar.vue
src/pages/Request/RequestMain.vue
src/store/action.js
src/store/getter.js
src/store/mutation.js

feat : request 검색 기능 추가

---

src/pages/Request/RequestWrite.vue

RequestWrite page Networking finish

feat : RequestWrite page Networking finish

---

src/pages/Request/RequestMain.vue

request main counting function added

feat : request main counting function added

---

src/components/Poster/MainPoster.vue
src/components/Toolbar/Toolbar.vue
src/store/action.js
src/store/mutation.js

title, subtitle tag를 mainposter에 추가

feat : title, subtitle tag를 mainposter에 추가

---

src/components/Modal/Subscribe-modal.vue
src/pages/Subscribe/Subscribe.vue
src/store/action.js
src/store/getter.js
src/store/mutation.js
src/store/state.js

feat : subscription axios 완료

---

src/components/Toolbar/Toolbar.vue
src/pages/Request/MyRequest.vue
src/router/index.js
src/router/myPage.js
src/store/action.js
src/store/getter.js
src/store/mutation.js
src/store/state.js
src/store/store.js

feat : 내가 쓴 글 완료

---

package-lock.json
package.json
src/components/Toolbar/SearchBar.vue
src/components/Toolbar/Toolbar.vue
src/pages/Search.vue
src/store/action.js
src/store/getter.js
src/store/mutation.js
src/store/state.js
src/store/store.js

fix : 최근 검색 제거

---

src/components/Card/VideoCard.vue
src/components/Modal/Subscribe-modal.vue
src/components/Vi-Main/ViM-Infor.vue
src/components/Vi-Main/ViM-Video.vue
src/pages/Home.vue
src/pages/Subscribe/Subscribe.vue
src/pages/VideoContents.vue
src/router/video.js
src/store/action.js
src/store/getter.js
src/store/mutation.js
src/store/state.js
src/store/store.js

add : videocard 클릭 시 contents 연결

---

src/pages/Request/RequestWrite.vue
src/store/action.js

fix : change api of request list

fix : change api of request list
